### Tensors
They're similar to numpy arrays but can be used on GPU to accelerate computing

In [1]:
from __future__ import print_function
import torch

In [2]:
# create an empty, uninitialized matrix
x = torch.empty(5,3)
print(x)

tensor([[2.0975e-08, 4.5597e-41, 2.0975e-08],
        [4.5597e-41,        nan, 0.0000e+00],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.4603e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])


In [3]:
# create a randomly initialized matrix
# values are b/w 0 and 1
x = torch.rand(5,3)
print(x)

tensor([[0.3499, 0.6736, 0.4253],
        [0.0960, 0.6518, 0.0284],
        [0.4834, 0.1909, 0.8430],
        [0.2681, 0.7800, 0.5024],
        [0.4324, 0.3587, 0.3701]])


In [4]:
# create a matrix of zeros and specify the data type
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# use a list to construct a tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# we can also create tensors from existing tensors
x = x.new_ones(5,3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [7]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.6245, 0.7436, 0.8553],
        [0.8611, 0.3620, 0.3921],
        [0.9170, 0.9288, 0.0605],
        [0.7024, 0.7748, 0.6716],
        [0.2699, 0.5125, 0.5972]])


In [8]:
x.size()

torch.Size([5, 3])

### Operations on tensors

In [9]:
y = torch.rand(5,3)
print(x+y)

tensor([[0.7557, 0.7872, 1.7344],
        [1.4174, 1.1016, 0.7681],
        [1.2491, 1.8127, 0.2266],
        [0.9429, 1.3028, 1.5837],
        [0.7508, 1.2086, 1.2896]])


In [10]:
print(torch.add(x,y))

tensor([[0.7557, 0.7872, 1.7344],
        [1.4174, 1.1016, 0.7681],
        [1.2491, 1.8127, 0.2266],
        [0.9429, 1.3028, 1.5837],
        [0.7508, 1.2086, 1.2896]])


In [11]:
result = torch.add(x,y)

In [12]:
result

tensor([[0.7557, 0.7872, 1.7344],
        [1.4174, 1.1016, 0.7681],
        [1.2491, 1.8127, 0.2266],
        [0.9429, 1.3028, 1.5837],
        [0.7508, 1.2086, 1.2896]])

In [13]:
# another way to do it
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7557, 0.7872, 1.7344],
        [1.4174, 1.1016, 0.7681],
        [1.2491, 1.8127, 0.2266],
        [0.9429, 1.3028, 1.5837],
        [0.7508, 1.2086, 1.2896]])


In [14]:
# every function in pytorch which comes with an underscore
# means the operation takes place in place
y.add_(x)
print(y)

tensor([[0.7557, 0.7872, 1.7344],
        [1.4174, 1.1016, 0.7681],
        [1.2491, 1.8127, 0.2266],
        [0.9429, 1.3028, 1.5837],
        [0.7508, 1.2086, 1.2896]])


In [15]:
# indexing in pytorch is similar to numpy
print(x)
print(x[:,1])

tensor([[0.6245, 0.7436, 0.8553],
        [0.8611, 0.3620, 0.3921],
        [0.9170, 0.9288, 0.0605],
        [0.7024, 0.7748, 0.6716],
        [0.2699, 0.5125, 0.5972]])
tensor([0.7436, 0.3620, 0.9288, 0.7748, 0.5125])


In [16]:
# you can use torch.view for resizing or reshaping
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
# if we have one element tensors then we can use .item to get the value
# as a python number
x = torch.tensor([3.14])

In [18]:
print(x)
print(x.item())

tensor([3.1400])
3.140000104904175


### Numpy bridge

In [19]:
a = torch.ones(4)
a

tensor([1., 1., 1., 1.])

In [20]:
b = a.numpy()
b

array([1., 1., 1., 1.], dtype=float32)

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [23]:
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
np.add(a, 1, out = a)

array([2., 2., 2., 2., 2.])

In [25]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([4.1400], device='cuda:0')
tensor([4.1400], dtype=torch.float64)
