In [1]:
import torch

In [2]:
def activation(x):
    """Sigmoid activation function
    
       Arguments
       ================
       x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
# set the seed for generating random numbers
torch.manual_seed(7)

In [4]:
features  = torch.randn((1,5))
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [5]:
weights = torch.randn_like(features)
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [6]:
bias = torch.randn((1,1))
bias

tensor([[0.3177]])

In [7]:
output = activation(torch.sum(features * weights) + bias)
output

tensor([[0.1595]])

we can do the same operations using matrix mul. the two options for that are `torch.mm` or `torch.matmul`
`torch.matmul` supports broadcasting while `torch.mm` is stricter. Prefer `torch.mm` 

In [8]:
features.shape

torch.Size([1, 5])

In [9]:
weights.shape

torch.Size([1, 5])

we will have to reshape our weights to do matrix multiplication. The options for this are

`weights.reshape(a,b)`: new tensor with new weights. Data either sits in the same part in memory or sometimes gets copied to another part

`weights.resize_(a,b)`: underscore means it is an inplace opearation. The problem with this method is if the new dimensions are small you can lose some of the data and if they are large, new memory parts will be uninitialized.

`weights.view(a,b)`: returns new tensor without copying data in memory. Preferred. If the dims don't match, it will throw an error

In [10]:
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [11]:
outputs_mm = activation(torch.mm(features, weights.view(5,1)) + bias)
outputs_mm

tensor([[0.1595]])

In [12]:
print(output)
print(outputs_mm)

tensor([[0.1595]])
tensor([[0.1595]])


## Multi layer neural net

In [13]:
torch.manual_seed(7)

In [14]:
features = torch.randn(1,3)
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [15]:
n_inputs = features.shape[1]
n_inputs

3

In [16]:
n_hidden = 2
n_outputs = 1

In [17]:
# weights from input to hidden layers
W1 = torch.randn(n_inputs, n_hidden)
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [18]:
# weights from hidden to output layers
W2 = torch.randn(n_hidden, n_outputs)
W2

tensor([[-1.6822],
        [ 0.3177]])

In [19]:
# bias for the hidden layer
B1 = torch.randn(1, n_hidden)
B1

tensor([[0.1328, 0.1373]])

In [20]:
B2 = torch.randn(1, n_outputs)
B2

tensor([[0.2405]])

In [21]:
output_hidden = activation(torch.mm(features, W1) + B1)
output_hidden

tensor([[0.6813, 0.4355]])

In [22]:
output_multi = activation(torch.mm(output_hidden, W2) + B2)
output_multi

tensor([[0.3171]])

## Numpy to torch and back

Often we might be doing some preprocessing with our data using numpy and we want to easily convert it to a tensor

In [23]:
import numpy as np

In [24]:
a = np.random.rand(4,3)
a

array([[0.3846791 , 0.44755024, 0.78109232],
       [0.34958295, 0.30560956, 0.66427252],
       [0.99124454, 0.57651713, 0.11246573],
       [0.37422729, 0.91175393, 0.50258437]])

In [25]:
b = torch.from_numpy(a)
b

tensor([[0.3847, 0.4476, 0.7811],
        [0.3496, 0.3056, 0.6643],
        [0.9912, 0.5765, 0.1125],
        [0.3742, 0.9118, 0.5026]], dtype=torch.float64)

In [26]:
b.numpy()

array([[0.3846791 , 0.44755024, 0.78109232],
       [0.34958295, 0.30560956, 0.66427252],
       [0.99124454, 0.57651713, 0.11246573],
       [0.37422729, 0.91175393, 0.50258437]])

Note that memory is shared b/w the numpy array and the tensor so if you are going to change one the other one will change as well

In [27]:
# multiply every number by 2
b.mul_(2)

tensor([[0.7694, 0.8951, 1.5622],
        [0.6992, 0.6112, 1.3285],
        [1.9825, 1.1530, 0.2249],
        [0.7485, 1.8235, 1.0052]], dtype=torch.float64)

In [28]:
a

array([[0.7693582 , 0.89510049, 1.56218463],
       [0.69916589, 0.61121912, 1.32854504],
       [1.98248908, 1.15303425, 0.22493146],
       [0.74845458, 1.82350787, 1.00516875]])